<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="CRUISe_DealTasks_Regression_Suite" duration-ms="38722" started-at="2020-06-03T11:49:24Z" finished-at="2020-06-03T11:50:03Z">
    <groups>
    </groups>
    <test name="Click flight" duration-ms="38722" started-at="2020-06-03T11:49:24Z" finished-at="2020-06-03T11:50:03Z">
      <class name="test.framework.TestBookFlight">
        <test-method status="PASS" signature="setup()[pri:0, instance:test.framework.TestBookFlight@55f3ddb1]" name="setup" is-config="true" duration-ms="12136" started-at="2020-06-03T14:49:24Z" finished-at="2020-06-03T14:49:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="selectFlightPage()[pri:0, instance:test.framework.TestBookFlight@55f3ddb1]" name="selectFlightPage" duration-ms="25091" started-at="2020-06-03T14:49:36Z" description="Demo ---&gt; xpedia site " finished-at="2020-06-03T14:50:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The values are not egual expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The values are not egual expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at test.framework.TestBookFlight.selectFlightPage(TestBookFlight.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectFlightPage -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.framework.TestBookFlight@55f3ddb1]" name="tearDown" is-config="true" duration-ms="677" started-at="2020-06-03T14:50:02Z" finished-at="2020-06-03T14:50:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.framework.TestBookFlight -->
    </test> <!-- Click flight -->
  </suite> <!-- CRUISe_DealTasks_Regression_Suite -->
</testng-results>
